import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function Home() {
  const { push,replace }=useRouter();
  function handleClick(){
    console.log("Placing your order");
    replace("/product");
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Home Page</h1>
        <Link href="blog"><h3>Blog</h3></Link>
        <Link href="product"><h3>Product</h3></Link>
        <button onClick={handleClick}>Place Order</button>
      </main>
    </div>
  )
}
